name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '* * * * *'
  workflow_dispatch:
  
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "True"
          SHOW_PROJECTS: "False"
          #LOCALE: 
          #COMMIT_BY_ME: "True"
          #COMMIT_MESSAGE: "Updated by Induwara Uthsara"
          #COMMIT_USERNAMECOMMIT_USERNAME: 
          #COMMIT_EMAIL: 
          SHOW_UPDATED_DATE: "True"
          UPDATED_DATE_FORMAT: "%d/%m/%Y %H:%M:%S"
          SHOW_LINES_OF_CODE: "True"
          SHOW_TOTAL_CODE_TIME: "True"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LANGUAGE: "True"
          SHOW_TIMEZONE: "True"
          SHOW_EDITORS: "True"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_SHORT_INFO: "True"
          SYMBOL_VERSION: 2
          SHOW_LOC_CHART: "False"
          #IGNORED_REPOS: 

          #site : https://github.com/marketplace/actions/profile-readme-development-stats